### ISSUE TITLE
Occasional execution stucks when calling close()

### ISSUE THREAD

**Issue by 3ohne** [EmbedME/pyUSBlini#1]
Hey Thomas, great work with the usblini. Unfortunately I have an issue with using the device library repeatedly. Sometimes the execution stucks in close() call and I have to interrupt execution with KeyboardInterrupt.

For trying to reproduce just execute the following instructions multiple times.

```
from usblini import USBlini
lin = USBlini()
lin.open()
lin.close()
```

Sometimes I need to repeat it ten times to reproduce it but most of the time lesser executions are necessary. Once it occurs it feels like its more often occurring after until you unplug the device and plug it in again.

Might it be possible for you to try it and give me feedback if you are able to reproduce it?

**Comment by EmbedME** [comment]
Hello, Thank you for reporting this issue! Yes, I can reproduce the problem. It seems that following line hangs:

https://github.com/EmbedME/pyUSBlini/blob/d874af283d6bdf8b79c1bdd468f42cb1d8bf4f86/usblini/usblini.py#L97

Unfortunately, I do not see at the moment what is causing the problem. 

Execution with KeyboardInterrupt stops in __libusb_handle_events(). Hmm...

**Comment by 3ohne** [comment]
Yeah that's what I also found.

**Comment by 3ohne** [comment]
Didn't want to close it...

That's what I found too. Will try to investigate it a little bit.

**Comment by 3ohne** [comment]
Closing was a missclick...

I tried to isolate the error and it seems that it occurs in relation with USBTransferHelper `th2`. I tested with `th1` only and called `open()` and `close()` in a loop a 1000 times without any problems.

With only `th2` it hangs after some iterations.

After I checked that this endpoint is only used for logic listening functions I disabled `th2` and it's working flawlessly for now.

**Comment by EmbedME** [comment]
Thank you for the investigations!

If the usb transfers are prevented from being resubmitted ("doom()") before closing, it seems that the close() always works. Can you confirm this?

Changes: [Stop submitting usb transfers before closing](https://github.com/EmbedME/pyUSBlini/commit/42fb19f60c18821445ea38b5c730eb5e11294773)

**Comment by EmbedME** [comment]
Current status: The problem with close() still exists. The most frequent error message now is 
ValueError('Cannot close a submitted transfer').

... needs further investigation.

**Comment by EmbedME** [comment]
This issue was solved with a few modifications to the USB transfer handling: https://github.com/EmbedME/pyUSBlini/commit/2977cd34f905561825fccaa619ee5f286ab1dd5c
