### ISSUE TITLE
Master Rx data

### ISSUE THREAD

**Issue by alexlinno** [EmbedME/pyUSBlini#4]
Hi , in the GUI example application. we do see Tx and Tx Data from the master (USBLini as master here). but we don't see Rx data from the slave. On both scope and the pulseview recording we see that data is sent from the slave. Is Rx data from the slave shown in the application?
On the application of the MicroChip USB to Lin  device we see rx data in its application
any tips ?

**Comment by EmbedME** [comment]
Hello! Yes, the answer from slave should be shown in the GUI.

Please can you provide these two files which include RX data but not shown in the GUI:
1. Logic recording (tab "Logic") and
2. Main window log (bottom of main window -> "Save")

**Comment by alexlinno** [comment]
[log.txt](https://github.com/EmbedME/pyUSBlini/files/11259200/log.txt)
[test (1).sr.txt](https://github.com/EmbedME/pyUSBlini/files/11259205/test.1.sr.txt)
hope you can read the sr file..
[test.pvs.txt](https://github.com/EmbedME/pyUSBlini/files/11259210/test.pvs.txt)

**Comment by EmbedME** [comment]
Your message does not meet the LIN specification. The response time is too long. Please see the Pulseview analysis (Pulseview also marks the response with error):

![test_pulseview](https://user-images.githubusercontent.com/5411323/232715991-7cc0f630-06b2-437a-b5e6-3f8db03697d4.png)

Your frame time is ~10.8ms
Maximum frame time allowed by the LIN specification: (1.4 * ((2*10) + 44)) * (1/19200) = ~4.7ms
[Calculation of the maximum allowed frame time.](https://microchipdeveloper.com/local--files/lin:protocol-dll-frame-timing/lin-message-frame-max.png)

Which slave do you use? Are you developing the slave (which microcontroller? has it uart fifos that delay the processing/response?)

**Comment by alexlinno** [comment]
Is there a possibility to set the max frame length... We are developing a lin slave.. But we don't need to compatible

**Comment by EmbedME** [comment]
Timeouts are set in [USBlini firmware](https://www.fischl.de/usblini/#firmwarepackage). File "lin.c", function "lin_setBaudrate":
```
timeoutpreset_intrabyte = (uint16_t)(200000 / baudrate); // 100 kHz / 8 / baudrate * 16   
timeoutpreset_response =  (uint16_t)(652000 / baudrate); // 100 kHz / 8 / baudrate * 50   
```
This is from USBlini_firmware_v1.01 and means:
intrabyte: 16 tbit, response: 50 tbit

**Comment by alexlinno** [comment]
Thanks for your support...ashamed to say that printf delayed the code
