### ISSUE TITLE
usblini.usblini.USBliniError

### ISSUE THREAD

**Issue by nico0481** [EmbedME/pyUSBlini#5]
Hello, where following issue could com from?

>>> ulini.master_write(0x00,USBlini.CHECKSUM_MODE_NONE,[])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/dist-packages/usblini-1.1-py3.11.egg/usblini/usblini.py", line 217, in master_write
    raise USBliniError()
usblini.usblini.USBliniError
>>>

**Comment by nico0481** [comment]
Hi,

Error seems raised when not connected on the Bus.

Now I get a response, but other error:

└─$ sudo python detect.py
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- 1d 1e -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
Exception ignored on calling ctypes callback function: <bound method USBTransfer.__callbackWrapper of <class 'usb1.USBTransfer'>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/libusb1-3.0.0-py3.11.egg/usb1/__init__.py", line 329, in __callbackWrapper
    self.close()
  File "/usr/local/lib/python3.11/dist-packages/libusb1-3.0.0-py3.11.egg/usb1/__init__.py", line 263, in close
    raise ValueError('Cannot close a submitted transfer')
ValueError: Cannot close a submitted transfer

**Comment by EmbedME** [comment]
> in master_write raise USBliniError()

The master write generate an error if the character sent (e.g. the PID) cannot be read back during transmission (MISSING_ECHO). As you mentioned, this error should not occur if the bus is connected correctly (Vbat applied, master-pullup active).

> in close raise ValueError('Cannot close a submitted transfer')

This will be this known issue: https://github.com/EmbedME/pyUSBlini/issues/1

**Comment by EmbedME** [comment]
There are improvements to both points:

> in master_write raise USBliniError()

Added a more detailed error message: https://github.com/EmbedME/pyUSBlini/commit/88f9f1018d569e953789a746129b112e7b0a1bdb

> in close raise ValueError('Cannot close a submitted transfer')

Modified USB transfer handling so this error no longer occurs: https://github.com/EmbedME/pyUSBlini/commit/2977cd34f905561825fccaa619ee5f286ab1dd5c

Thank you for reporting this issues!
