### ISSUE TITLE
GUI slave setting - reload, reset

### ISSUE THREAD

**Issue by lechndo** [EmbedME/pyUSBlini#6]
Hi,

my company recently bought USBlini for some reverse engineering task and until now I see it as a great tool, especially because of the Python interface.

I started with using the GUI for creating traces and I just came across the slave setting fields "Reload" and "Reset".
Could someone please tell me how the settings work or what they are supposed to do, because I could not find it out myself.

Thx,

**Comment by EmbedME** [comment]
Thank you for your message! I'm glad you like USBlini. Unfortunately, there hasn't been any documentation on "Reload" and "Reset" in slave mode so far. Thank you for pointing that out! The readme has been updated accordingly. I hope this clarifies the purpose of these fields:
https://github.com/EmbedME/pyUSBlini/tree/main#slave

**Comment by lechndo** [comment]
Thx for enhancing the docu.

One more question...
Are the 16 slave slots - mentioned in the description - a device limit or just a limit of the GUI?
For more complexe sequences and setups more slots would be useful...
Could the number of slots be expanded in the device firmware?

**Comment by EmbedME** [comment]
> Are the 16 slave slots - mentioned in the description - a device limit or just a limit of the GUI?

The 16 slave slots are a device/firmware limit.

> Could the number of slots be expanded in the device firmware?

In file linslave.h you find
#define SLAVETABLE_SIZE 16
Please note that there are dependencies on the table size, such as the size of reset bitmask (uint16_t).

**Comment by lechndo** [comment]
> In file linslave.h you find 
> #define SLAVETABLE_SIZE 16 
> Please note that there are dependencies on the table size, such as the size of reset bitmask (uint16_t).

Thx for pointing that out. I already had a look on it.
I hope we don't have to adapt the device firmware... but really love the fact that we can, if we have to :-)

Thx again for this great tool. ;-)
